#:schema node_modules/wrangler/config-schema.json
name = "horse-racing-duckdb"
main = "src/app.ts"
compatibility_date = "2025-02-07"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false
